name: CMake
on: [push]
jobs:
  build:
    runs-on: ${{matrix.os}}
    container: ${{matrix.container}}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            cxx: g++-10
          - os: ubuntu-latest
            cxx: clang++-12
          - os: windows-latest
          - os: ubuntu-latest
            container: emscripten/emsdk
            emcmake: emcmake
    steps:
      - uses: actions/checkout@v2
      - name: Create Build Environment
        run: cmake -E make_directory build
      - name: Configure CMake
        env:
          CXX: ${{matrix.cxx}}
        working-directory: build
        run: ${{matrix.emcmake}} cmake .. -DCMAKE_BUILD_TYPE=Debug
      - name: Build
        working-directory: build
        run: cmake --build .
      - name: Test
        working-directory: build
        run: ctest -C Debug
