name: CMake
on: [push]
jobs:
  build:
    runs-on: ${{matrix.os}}
    container: ${{matrix.container}}
    strategy:
      matrix:
        tool: [gcc, clang, emscripten, msvc]
        configuration: [Debug, Release]
        include:
          - tool: gcc
            os: ubuntu-24.04
            cxx: g++-14
          - tool: clang
            os: ubuntu-24.04
            cxx: clang++-18
          - tool: emscripten
            os: ubuntu-latest
            container: emscripten/emsdk
            emcmake: emcmake
          - tool: msvc
            os: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Build Environment
        run: cmake -E make_directory build
      - name: Configure CMake
        env:
          CXX: ${{matrix.cxx}}
        working-directory: build
        run: ${{matrix.emcmake}} cmake .. -DCMAKE_BUILD_TYPE=${{matrix.configuration}}
      - name: Build
        working-directory: build
        run: cmake --build . --config ${{matrix.configuration}}
      - name: Test
        working-directory: build
        run: ctest -C ${{matrix.configuration}} -VV
